### ISSUE TITLE
mini-dinstall -k daemon doesn't exit

### ISSUE THREAD

**Issue by connortechnology** [shartge/mini-dinstall#4]
mini-dinstall in ubuntu focal.  Last logs are as follows:
Nov 29 12:41:34 mini-dinstall [140423326582528] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:34 mini-dinstall [140423267862272] INFO: Thread "focal" exiting
Nov 29 12:41:34 mini-dinstall [140423301404416] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:34 mini-dinstall [140423564846848] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:34 mini-dinstall [140423974835968] INFO: Thread "stretch" exiting
Nov 29 12:41:35 mini-dinstall [140423318189824] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:35 mini-dinstall [140423276254976] INFO: Thread "eoan" exiting
Nov 29 12:41:35 mini-dinstall [140423343367936] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:35 mini-dinstall [140423983228672] INFO: Thread "jessie" exiting
Nov 29 12:41:35 mini-dinstall [140424000014080] INFO: All packages in incoming dir installed; exiting
Nov 29 12:41:35 mini-dinstall [140424025282368] INFO: Die event caught; waiting for archive wheezy to finish
Nov 29 12:41:35 mini-dinstall [140423603410688] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:35 mini-dinstall [140423966443264] INFO: Thread "sid" exiting
Nov 29 12:41:35 mini-dinstall [140423595017984] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:35 mini-dinstall [140423259469568] INFO: Thread "groovy" exiting
Nov 29 12:41:35 mini-dinstall [140423573239552] INFO: Thread "bionic" exiting
Nov 29 12:41:35 mini-dinstall [140423309797120] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:35 mini-dinstall [140423586625280] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:35 mini-dinstall [140423351760640] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:35 mini-dinstall [140423991621376] INFO: Thread "wheezy" exiting
Nov 29 12:41:35 mini-dinstall [140424025282368] INFO: Die event caught; waiting for archive jessie to finish
Nov 29 12:41:35 mini-dinstall [140424025282368] INFO: Die event caught; waiting for archive stretch to finish
Nov 29 12:41:35 mini-dinstall [140424025282368] INFO: Die event caught; waiting for archive sid to finish
Nov 29 12:41:35 mini-dinstall [140424025282368] INFO: Die event caught; waiting for archive trusty to finish
Nov 29 12:41:35 mini-dinstall [140423620196096] INFO: Thread "trusty" exiting
Nov 29 12:41:35 mini-dinstall [140424025282368] INFO: Die event caught; waiting for archive xenial to finish
Nov 29 12:41:35 mini-dinstall [140423334975232] INFO: Caught cancel event; async dnotify thread exiting
Nov 29 12:41:35 mini-dinstall [140423284647680] INFO: Thread "buster" exiting

process is still running, further mini-dinstall -k's hang waiting on a FUTEX.

**Comment by shartge** [comment]
I am not the maintainer for mini-dinstall, this is not the main repository but just a private and outdated fork.

Please redirect your question and bug to the real developers at https://salsa.debian.org/debian/mini-dinstall
